name: Test workflow
on:
  workflow_dispatch:
env:
  # --- Secrets (from your list) ---
  ARXIV_QUERY: ${{ secrets.ARXIV_QUERY }}
  LANGUAGE: ${{ secrets.LANGUAGE }}
  MODEL_NAME: ${{ secrets.MODEL_NAME }}
  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  RECEIVER: ${{ secrets.RECEIVER }}
  SENDER: ${{ secrets.SENDER }}
  SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
  USE_LLM_API: ${{ secrets.USE_LLM_API }}
  ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
  ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}

  # --- Vars (repo/org env vars) ---
  REPOSITORY: ${{ vars.REPOSITORY }}
  REF: ${{ vars.REF }}
  ZOTERO_IGNORE: ${{ vars.ZOTERO_IGNORE }}
  SEND_EMPTY: ${{ vars.SEND_EMPTY }}
  
jobs:
  calculate-and-send:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_IGNORE: ${{ vars.ZOTERO_IGNORE }}
          ARXIV_QUERY: ${{ secrets.ARXIV_QUERY }}
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MAX_PAPER_NUM: ${{ secrets.MAX_PAPER_NUM }}
          USE_LLM_API: ${{ secrets.USE_LLM_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          LANGUAGE: ${{ vars.LANGUAGE }}
        run: |
          uv run main.py --debug
